name: Deploy Plugin to Minecraft
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven/Gradle
        run: mvn clean package -Dskiptests
      - name: Deploy to Server via SFTP
        uses: appleboy/scp-action@v1
        with:
          source: target/SoulmatePlugin.jar
          target: ~/minecraft/plugins/
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          strip_components: 1
          overwrite: true
      #- name: Reload Plugins via RCON
      #  run: |
      #    sudo apt-get install mcrcon -y
      #    mcrcon -H ${{ secrets.REMOTE_HOST }} -P 25575 -p ${{ secrets.RCON_PASSWORD }} "plugman reload x"